name: jk_multi_world
version: '1.0-SNAPSHOT'
main: jiekie.multiworld.MultiWorldPlugin
api-version: '1.20'
authors: [Jiekie]
description: 월드 관리 플러그인
depend: [jk_nickname]
commands:
  월드:
    description: 월드 설정 명령어
    usage: /월드
    tab-completer: jiekie.multiworld.completer.MultiWorldTabCompleter
    permission: jk.multi_world.command
    permission-message: ''